version: '2'
services:
  nginx:
#    build:
#      context: ./
#      dockerfile: docker/nginx/Dockerfile
    image: nginx:1.15
#    volumes:
#      - ./:/var/www
    volumes:
      - ./docker/nginx/configs:/etc/nginx/conf.d
      - ./:/var/www
      - .//logs:/var/log/nginx
    ports:
      - "8080:80"
    links:
      - php-fpm
  php-cli:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www
    links:
      - mysql
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www
    links:
      - mysql
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
  mysql:
    image: mysql:5.7
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=app"
    ports:
      - "33062:3306"
  pma:
    # используем последний стабильный образ phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0.2
    restart: always
    links:
      - mysql:mysql
    ports:
      - 51113:80
    environment:
      # прописываем название нашего MySQL хоста
      PMA_HOST: mysql
      MYSQL_USERNAME: app
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
